# Generated by Django 4.0.6 on 2022-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std_model',
            fields=[
                ('personal_No', models.IntegerField(primary_key=True, serialize=False)),
                ('std_personal_No', models.IntegerField()),
                ('stdname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
