# Generated by Django 4.0.6 on 2022-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibralianModel',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('libralian_no', models.IntegerField()),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
